const productos = [
  {
    id: 1,
    nombre: "PROBI GO!",
    precio: 1098,
    presentacion: "Caja con 30 stickpacks de 2g",
    categoria: "Digestión",
    imagen: "https://via.placeholder.com/300x250/4CAF50/FFFFFF?text=PROBI+GO%21",
    ingredientes: [
      "Lactobacillus rhamnosus",
      "Lactiplantibacillus plantarum",
      "Bifidobacterium animalis",
      "Inulina",
      "FOS",
      "XOS",
      "Dextrina resistente",
      "Arándano",
      "Vitamina D3",
      "Zinc"
    ],
    beneficios: [
      "Mantiene microbiota intestinal equilibrada",
      "Fortalece defensas naturales",
      "Favorece absorción de nutrientes",
      "Protege mucosa intestinal",
      "Aporta antioxidantes"
    ],
    modoUso: "Tomar 1 stickpack al día, directamente o disuelto en 240 ml de agua",
    descripcionCorta: "Digestión equilibrada y defensas fuertes",
    descripcionLarga: "PROBI GO! es un suplemento avanzado con prebióticos, probióticos y postbióticos que ayuda a mantener una microbiota intestinal saludable, fortalece las defensas naturales y favorece la absorción de nutrientes."
  },
  {
    id: 2,
    nombre: "ZENDRA",
    precio: 807,
    presentacion: "Frasco con 60 cápsulas de 750mg",
    categoria: "Mental",
    imagen: "https://via.placeholder.com/300x250/9C27B0/FFFFFF?text=ZENDRA",
    ingredientes: ["Ashwagandha","Melena de León","Bacopa"],
    beneficios: [
      "Reduce estrés y cortisol",
      "Favorece memoria y concentración",
      "Apoya salud cerebral",
      "Aumenta energía sin cafeína",
      "Mejora sueño y bienestar emocional"
    ],
    modoUso: "Tomar 2 cápsulas al día (1 mañana, 1 noche)",
    descripcionCorta: "Reduce el estrés y mejora tu memoria",
    descripcionLarga: "ZENDRA es tu aliado para el equilibrio mental y emocional. Con Ashwagandha, Melena de León y Bacopa, ayuda a reducir el estrés, favorece la memoria y concentración, y apoya la salud cerebral integral."
  },
  {
    id: 3,
    nombre: "BELMESE",
    precio: 456,
    presentacion: "Caja con 30 cápsulas",
    categoria: "Mujeres",
    imagen: "https://via.placeholder.com/300x250/E91E63/FFFFFF?text=BELMESE",
    ingredientes: ["Vitamina B","Hierro","Ácido fólico"],
    beneficios: ["Equilibrio hormonal","Energía","Bienestar emocional"],
    modoUso: "1 cápsula diaria",
    descripcionCorta: "Equilibrio hormonal y bienestar para la mujer",
    descripcionLarga: "BELMESE es un suplemento especializado para la salud integral de la mujer, diseñado para mantener el equilibrio hormonal y proporcionar energía durante todo el día."
  },
  {
    id: 4,
    nombre: "VITAHOMBRE",
    precio: 650,
    presentacion: "Frasco con 60 cápsulas",
    categoria: "Hombres",
    imagen: "https://via.placeholder.com/300x250/1976D2/FFFFFF?text=VITAHOMBRE",
    ingredientes: ["Zinc","Ginseng","L-Arginina"],
    beneficios: ["Virilidad","Resistencia","Salud sexual"],
    modoUso: "2 cápsulas al día",
    descripcionCorta: "Virilidad y resistencia para el hombre",
    descripcionLarga: "VITAHOMBRE potencia tu virilidad y resistencia con ingredientes naturales seleccionados para la salud masculina integral."
  },
  {
    id: 5,
    nombre: "KIDVITA",
    precio: 380,
    presentacion: "Botella de 200ml",
    categoria: "Niños",
    imagen: "https://via.placeholder.com/300x250/FF9800/FFFFFF?text=KIDVITA",
    ingredientes: ["Vitaminas","Minerales","Probióticos"],
    beneficios: ["Crecimiento","Inmunidad","Desarrollo cognitivo"],
    modoUso: "15ml una vez al día",
    descripcionCorta: "Vitaminas y minerales para el crecimiento sano",
    descripcionLarga: "KIDVITA asegura que los niños obtengan todos los nutrientes esenciales para un crecimiento y desarrollo óptimo."
  },
  {
    id: 6,
    nombre: "BEAUTYBLOOM",
    precio: 520,
    presentacion: "Caja con 30 cápsulas",
    categoria: "Belleza",
    imagen: "https://via.placeholder.com/300x250/FF1493/FFFFFF?text=BEAUTYBLOOM",
    ingredientes: ["Colágeno","Biotina","Vitamina E"],
    beneficios: ["Piel radiante","Cabello fuerte","Uñas saludables"],
    modoUso: "2 cápsulas diarias",
    descripcionCorta: "Belleza radiante desde adentro",
    descripcionLarga: "BEAUTYBLOOM es tu secreto para una piel radiante, cabello brillante y uñas fuertes, todo con ingredientes naturales."
  },
  {
    id: 7,
    nombre: "DEFENSAL",
    precio: 625,
    presentacion: "Frasco con 60 cápsulas",
    categoria: "Inmunológico",
    imagen: "https://via.placeholder.com/300x250/00BCD4/FFFFFF?text=DEFENSAL",
    ingredientes: ["Vitamina C","Zinc","Equinácea"],
    beneficios: ["Inmunidad reforzada","Protección contra virus","Recuperación rápida"],
    modoUso: "1 cápsula diaria",
    descripcionCorta: "Defensas naturales fortalecidas",
    descripcionLarga: "DEFENSAL potencia tu sistema inmunológico con una combinación científica de ingredientes para una protección integral."
  },
  {
    id: 8,
    nombre: "DETOXPURE",
    precio: 780,
    presentacion: "Caja con 28 sobres",
    categoria: "Desintoxicación",
    imagen: "https://via.placeholder.com/300x250/7CB342/FFFFFF?text=DETOXPURE",
    ingredientes: ["Cúrcuma","Carbón activado","Diente de león"],
    beneficios: ["Desintoxicación","Limpieza de hígado","Digestión mejorada"],
    modoUso: "1 sobre al día en agua",
    descripcionCorta: "Desintoxica tu cuerpo naturalmente",
    descripcionLarga: "DETOXPURE limpia y desintoxica tu organismo con ingredientes naturales que apoyan la función hepática y digestiva."
  },
  {
    id: 9,
    nombre: "ENERGIZE",
    precio: 450,
    presentacion: "Frasco con 60 gomas",
    categoria: "Energía",
    imagen: "https://via.placeholder.com/300x250/FFC107/FFFFFF?text=ENERGIZE",
    ingredientes: ["Cafeína natural","Guaraná","Ginseng"],
    beneficios: ["Energía prolongada","Sin crash","Concentración"],
    modoUso: "1-2 gomas según necesidad",
    descripcionCorta: "Energía natural sin estimulantes",
    descripcionLarga: "ENERGIZE te proporciona energía sostenida sin los efectos secundarios de la cafeína sintética."
  },
  {
    id: 10,
    nombre: "GLUCOCONTROL",
    precio: 890,
    presentacion: "Frasco con 90 cápsulas",
    categoria: "Glucosa",
    imagen: "https://via.placeholder.com/300x250/D32F2F/FFFFFF?text=GLUCOCONTROL",
    ingredientes: ["Canela","Cromo","Berberina"],
    beneficios: ["Control de glucosa","Metabolismo","Energía estable"],
    modoUso: "1 cápsula 3 veces al día",
    descripcionCorta: "Control glucémico naturalmente",
    descripcionLarga: "GLUCOCONTROL ayuda a mantener niveles saludables de glucosa en sangre con ingredientes respaldados por la ciencia."
  },
  {
    id: 11,
    nombre: "CARDIOFLOW",
    precio: 720,
    presentacion: "Frasco con 60 cápsulas",
    categoria: "Circulación",
    imagen: "https://via.placeholder.com/300x250/C2185B/FFFFFF?text=CARDIOFLOW",
    ingredientes: ["Ómega 3","Coenzima Q10","Ajo"],
    beneficios: ["Circulación mejorada","Salud cardiovascular","Presión saludable"],
    modoUso: "2 cápsulas diarias",
    descripcionCorta: "Circulación y corazón saludable",
    descripcionLarga: "CARDIOFLOW promueve una circulación saludable y apoya la función cardiovascular con ingredientes naturales de calidad premium."
  },
  {
    id: 12,
    nombre: "FLEXIJOINT",
    precio: 550,
    presentacion: "Frasco con 60 cápsulas",
    categoria: "Articulaciones",
    imagen: "https://via.placeholder.com/300x250/FFAB40/FFFFFF?text=FLEXIJOINT",
    ingredientes: ["Glucosamina","Condroitina","Cúrcuma"],
    beneficios: ["Articulaciones flexibles","Movilidad","Alivio articular"],
    modoUso: "2 cápsulas diarias",
    descripcionCorta: "Articulaciones fuertes y flexibles",
    descripcionLarga: "FLEXIJOINT mantiene tus articulaciones saludables y ágiles, permitiéndote disfrutar de mayor movilidad y comodidad."
  }
];