const sucursales = [
  { ciudad: "Campeche", estado: "Campeche" },
  { ciudad: "Cancún", estado: "Quintana Roo" },
  { ciudad: "Cárdenas", estado: "Tabasco" },
  { ciudad: "Ciudad Juárez", estado: "Chihuahua" },
  { ciudad: "Ciudad Obregón", estado: "Sonora" },
  { ciudad: "Ciudad Nezahualcóyotl", estado: "Edomex" },
  { ciudad: "Coatzacoalcos", estado: "Veracruz" },
  { ciudad: "Comalcalco", estado: "Tabasco" },
  { ciudad: "Comitán", estado: "Chiapas" },
  { ciudad: "Córdoba", estado: "Veracruz" },
  { ciudad: "Coyoacán", estado: "CDMX" },
  { ciudad: "Culiacán", estado: "Sinaloa" },
  { ciudad: "Ecatepec", estado: "Edomex" },
  { ciudad: "Irapuato", estado: "Guanajuato" },
  { ciudad: "Los Mochis", estado: "Sinaloa" },
  { ciudad: "Mazatlán", estado: "Sinaloa" },
  { ciudad: "Mérida", estado: "Yucatán" },
  { ciudad: "Mexicali", estado: "Baja California" },
  { ciudad: "Mixquiahuala", estado: "Hidalgo" },
  { ciudad: "Monterrey", estado: "Nuevo León" },
  { ciudad: "Morelia", estado: "Michoacán" },
  { ciudad: "Oaxaca", estado: "Oaxaca" },
  { ciudad: "Pachuca", estado: "Hidalgo" },
  { ciudad: "Puebla", estado: "Puebla" },
  { ciudad: "Puerto Vallarta", estado: "Jalisco" },
  { ciudad: "Querétaro", estado: "Querétaro" },
  { ciudad: "Reynosa", estado: "Tamaulipas" },
  { ciudad: "San Cristóbal de las Casas", estado: "Chiapas" },
  { ciudad: "San Luis Potosí", estado: "San Luis Potosí" },
  { ciudad: "Tacámbaro", estado: "Michoacán" },
  { ciudad: "Tampico", estado: "Tamaulipas" },
  { ciudad: "Tapachula", estado: "Chiapas" },
  { ciudad: "Tuzitlán", estado: "Puebla" },
   { ciudad: "Vallejo", estado: "CDMX" },
];
